name: taskora
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.10.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  fonts:
    - family: Tajawal-Black
      fonts:
        - asset: assets/fonts/Tajawal-Black.ttf
    - family: Tajawal-ExtraBold
      fonts:
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
    - family: Tajawal-ExtraLight
      fonts:
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
    - family: Tajawal-Light
      fonts:
        - asset: assets/fonts/Tajawal-Light.ttf
    - family: Tajawal-Medium
      fonts:
        - asset: assets/fonts/Tajawal-Medium.ttf
    - family: Tajawal-Regular
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf

  assets:
    - assets/icons/
    - assets/icons/checkmark.svg
    - assets/icons/clock.svg
    - assets/icons/listsProfile.svg
    - assets/icons/notification.svg
    - assets/images/
    - assets/images/onBoadringImage.png
    - assets/images/profilePic.png

