// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'taskora';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String CHECKMARK = 'assets/icons/checkmark.svg';
  static const String CLOCK = 'assets/icons/clock.svg';
  static const String LISTSPROFILE = 'assets/icons/listsProfile.svg';
  static const String NOTIFICATION = 'assets/icons/notification.svg';
  static const String ONBOADRINGIMAGE = 'assets/images/onBoadringImage.png';
  static const String PROFILEPIC = 'assets/images/profilePic.png';
}
