// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String PROJECT_NAME = 'taskora';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String TAJAWAL_BLACK = 'Tajawal-Black';
  static const String TAJAWAL_EXTRABOLD = 'Tajawal-ExtraBold';
  static const String TAJAWAL_EXTRALIGHT = 'Tajawal-ExtraLight';
  static const String TAJAWAL_LIGHT = 'Tajawal-Light';
  static const String TAJAWAL_MEDIUM = 'Tajawal-Medium';
  static const String TAJAWAL_REGULAR = 'Tajawal-Regular';
}
